# http://docs.travis-ci.com/user/build-configuration/

sudo: required

language: python

python:
    - "3.4"

env:
    - DJANGO=1.8

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip
    - pip install django
    - pip3 install djangorestframework
    - pip3 install markdown
    - pip3 install django-filter

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - pip3 freeze
    - python3 --version

script:
    - date
    - ls -al
    - make models.log
    - ls -al
    - make test
    - ls -al
    - make check
