FORMAT: 1A
HOST: http://copadb.me

# Copa2015

Copa2015 is a simple API allowing consumers to view players/Teams

# Polls API Root [/]

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the url link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.


## Players Collection [/player]

### List of Players [GET]

+ Response 200 (application/json)

        [{
            "player": "Claudio Bravo"
            "team": "Chile"
            "position": "GK"
	        "goals": "0"
            "dob": "(1983-04-13) April 13, 1983 (age 32)"
            "club": "Barcelona"
        },
        {
            "player": "Eugenio Mena"
            "team": "Chile"
            "position": "DF"
            "dob": "(1988-07-18) July 18, 1988 (age 26)"
            "goals": "3" 
            "club": "Cruzeiro"
        }]

### get a player [/player/{player}]
+ Parameters
    + player (string) - Name of Player in the form of a string

## Country Collection [/country]


### List of Countries [GET]

+ Response 200 (application/json)

        [{
            "country": "Chile"
            "goals": 12
            "coach": "Jorge Sampaoli"
            "captain":  "Claudio Bravo"
            "top_scorer": "Eduardo Vargas"
        },
        {
            "country": "Mexico"
            "goals": 4
            "coach": "Miguel Herrera"
            "captain":  "Rafael Márquez"
            "top_scorer": "Matías Vuoso"
        }]

### get a country [/country/{country}]
+ Parameters
    + country (string) - Name of Country in the form of a string

## Matches Collection [/match]

### List of Matches [GET]

+ Response 200 (application/json)

        [{
            "match": "Chile-Uruguay"
            "country_one": "Chile"
            "country_two": "Uruguay"
            "scores":  "1–0"
            "man_of_the_match": "Alexis Sánchez"
            "match_date": "24 June 2015 (2015-06-24)\n20:30"
            "match_location": "Estadio Nacional, Santiago"
        }]

### get a match [/match/{match}]
+ Parameters
    + match (string) - ID of match in form of a string
